name: 编译检查

on: 
  [push]
  #workflow_dispatch

jobs:
  build:

    runs-on: macos-latest #ubuntu-latest macos-latest

    steps:
    # 指定分支
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5.2"
    - name: Build
      run: swift build
    - name: Run
      run: swift run AutomaticTask -h

      # run: swift run AutomaticTask --pic-forum ${{ secrets.PIC  }}
