name: 编译检查

on: 
  #[push]
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest #ubuntu-latest macos-latest

    steps:
    # 指定分支
    - uses: actions/setup-node@develop
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5.2"
    - name: Build
      run: swift build
    - name: Run
      run: swift run AutomaticTask -h

      # run: swift run AutomaticTask --pic-forum ${{ secrets.PIC  }}
