name: 自动任务

on: [push]
  #workflow_dispatch
  # 定时任务
  #schedule:
  #         ┌───────────────────── minute (0 - 59)
  #         │ ┌─────────────────── hour (0 - 23)
  #         │ │ ┌───────────────── day of the month (1 - 31)
  #         │ │ │ ┌─────────────── month (1 - 12 or JAN-DEC)
  #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         │ │ │ │ │                                   
  #         │ │ │ │ │
  #         │ │ │ │ │
  #         * * * * *
  #- cron:  '0 17 * * *'


jobs:
  build:

    runs-on: ubuntu-latest #ubuntu-latest macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5.2"
    - name: Build
      run: swift build
    - name: Run
      run: swift run AutomaticTask --bing-wallpaper --notice ${{ secrets.NOTICE }} --pic-forum ${{ secrets.PIC  }}

    - name: Commit files
      run: |
         git config --local user.email "yingguqing@gmail.com"
         git config --local user.name "yingguqing"
         git add Sources/AutomaticTask/Module/BingWallpaper/bing-wallpaper.json
         git add Sources/AutomaticTask/Module/BingWallpaper/README.md
         git add Sources/AutomaticTask/config.json
         git commit -m "update readme.md"

    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN  }}
         branch: main
