name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest #ubuntu-latest macos-latest

    steps:
    - uses: actions/checkout@v2
    #- uses: fwal/setup-swift@v1
      #with:
        #swift-version: "5.3.2"
    - name: Build
      run: swift build
    - name: Run
      run: swift run
